"""Shared game constants for backend auto-host flow."""

ROLE_VILLAGER = "VILLAGER"
ROLE_WEREWOLF = "WEREWOLF"
ROLE_GUARD = "GUARD"
ROLE_SEER = "SEER"
ROLE_WITCH = "WITCH"
ROLE_HUNTER = "HUNTER"
ROLE_CUPID = "CUPID"
ROLE_OILMAN = "OILMAN"
ROLE_FOOL = "FOOL"
ROLE_CURSED_WOLF = "CURSED_WOLF"

SIDE_VILLAGER = "villager"
SIDE_WEREWOLF = "werewolf"
SIDE_SPECIAL = "special"

ACTION_WEREWOLF_BITE = "WEREWOLF_BITE"
ACTION_GUARD_PROTECT = "GUARD_PROTECT"
ACTION_SEER_CHECK = "SEER_CHECK"
ACTION_WITCH_HEAL = "WITCH_HEAL"
ACTION_WITCH_POISON = "WITCH_POISON"
ACTION_SKIP = "SKIP"

WINNER_VILLAGERS = "villagers"
WINNER_WEREWOLVES = "werewolves"

AUTO_TASK_ROLE_REVEAL_SECONDS = 20
AUTO_TASK_NIGHT_START_SECONDS = 8
AUTO_TASK_NIGHT_RESOLVE_SECONDS = 5
AUTO_TASK_DAY_RESULT_SECONDS = 15
AUTO_TASK_DISCUSSION_SECONDS = 120
AUTO_TASK_VOTING_SECONDS = 60
AUTO_TASK_VOTE_RESULT_SECONDS = 10

ROLE_TURN_SECONDS = {
    ROLE_GUARD: 20,
    ROLE_WEREWOLF: 30,
    ROLE_WITCH: 30,
    ROLE_SEER: 20,
}

ROLE_ACTION_TYPE = {
    ROLE_GUARD: ACTION_GUARD_PROTECT,
    ROLE_WEREWOLF: ACTION_WEREWOLF_BITE,
    ROLE_WITCH: ACTION_SKIP,  # Witch may submit heal/poison/skip, handled specially.
    ROLE_SEER: ACTION_SEER_CHECK,
}

PUBLIC_ROLE_NAMES = {
    ROLE_GUARD: "Bảo vệ",
    ROLE_WEREWOLF: "Ma Sói",
    ROLE_WITCH: "Phù thủy",
    ROLE_SEER: "Tiên tri",
}
